CREATE SCHEMA "audit";
--> statement-breakpoint
CREATE SCHEMA "stg";
--> statement-breakpoint
CREATE TYPE "public"."merchant_scope_type" AS ENUM('merchant', 'canonical');--> statement-breakpoint
CREATE TYPE "public"."transaction_status" AS ENUM('success', 'failed');--> statement-breakpoint
CREATE TABLE "admin_sessions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"session_token_hash" text NOT NULL,
	"ip_address" varchar(64),
	"user_agent" text,
	"expires_at" timestamp NOT NULL,
	"last_used_at" timestamp DEFAULT now() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "admin_sessions_token_hash_unique" UNIQUE("session_token_hash")
);
--> statement-breakpoint
CREATE TABLE "admin_users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" varchar(320) NOT NULL,
	"full_name" varchar(120) NOT NULL,
	"password_hash" text NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "admin_users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "audit"."batch_issue_links" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"batch_id" uuid NOT NULL,
	"issue_id" bigint NOT NULL,
	"row_num" integer NOT NULL,
	"state" text DEFAULT 'ACTIVE' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"dataset" text NOT NULL,
	"error_type" text NOT NULL,
	"error_message" text NOT NULL,
	"raw_payload" jsonb NOT NULL
);
--> statement-breakpoint
CREATE TABLE "audit"."batches" (
	"batch_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"dataset" text NOT NULL,
	"status" text NOT NULL,
	"source_file" text NOT NULL,
	"failed_step" text,
	"failed_reason" text,
	"total_rows" integer DEFAULT 0 NOT NULL,
	"loaded_rows" integer DEFAULT 0 NOT NULL,
	"rejected_rows" integer DEFAULT 0 NOT NULL,
	"reject_rate" numeric(8, 6) DEFAULT '0' NOT NULL,
	"run_count" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"batch_public_id" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "audit"."ingestion_issues" (
	"issue_id" bigserial PRIMARY KEY NOT NULL,
	"issue_fingerprint" text NOT NULL,
	"dataset" text NOT NULL,
	"issue_kind" text NOT NULL,
	"conflict_merchant_key" uuid,
	"conflict_start_period" date,
	"conflict_end_period" date,
	"error_type" text NOT NULL,
	"error_message" text NOT NULL,
	"raw_payload" jsonb NOT NULL,
	"status" text DEFAULT 'OPEN' NOT NULL,
	"resolved_at" timestamp,
	"resolved_by_batch_id" uuid,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"last_seen_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "dim_category" (
	"category_id" integer PRIMARY KEY NOT NULL,
	"category" varchar(500) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "dim_cluster" (
	"cluster_id" bigint PRIMARY KEY NOT NULL,
	"cluster" varchar(500) NOT NULL,
	"branch" varchar(500) NOT NULL,
	"region" varchar(500) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "dim_merchant" (
	"merchant_key" uuid PRIMARY KEY NOT NULL,
	"keyword_code" varchar(500) NOT NULL,
	"merchant_name" varchar(500) NOT NULL,
	"uniq_merchant" varchar(500) NOT NULL,
	"cluster_id" bigint NOT NULL,
	"category_id" integer NOT NULL,
	CONSTRAINT "dim_merchant_keyword_code_key" UNIQUE("keyword_code")
);
--> statement-breakpoint
CREATE TABLE "dim_rule" (
	"rule_key" uuid PRIMARY KEY NOT NULL,
	"rule_merchant" uuid NOT NULL,
	"point_redeem" integer NOT NULL,
	"created_at" timestamp NOT NULL,
	"period" daterange NOT NULL
);
--> statement-breakpoint
CREATE TABLE "fact_cluster_point" (
	"point_key" uuid PRIMARY KEY NOT NULL,
	"month_year" date NOT NULL,
	"cluster_id" bigint NOT NULL,
	"total_point" bigint NOT NULL,
	"point_owner" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "fact_transaction" (
	"transaction_key" uuid PRIMARY KEY NOT NULL,
	"transaction_at" timestamp NOT NULL,
	"rule_key" uuid NOT NULL,
	"merchant_key" uuid NOT NULL,
	"status" "transaction_status" NOT NULL,
	"qty" integer DEFAULT 1 NOT NULL,
	"point_redeem" integer NOT NULL,
	"msisdn" varchar(20) NOT NULL,
	"created_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "merchant_canonical_map" (
	"merchant_key" uuid PRIMARY KEY NOT NULL,
	"canonical_merchant_key" uuid NOT NULL,
	"uniq_merchant" text NOT NULL,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "merchant_feedback" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "merchant_feedback_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"merchant_key" uuid NOT NULL,
	"user_id" bigint NOT NULL,
	"type" text NOT NULL,
	"category" text NOT NULL,
	"title" text NOT NULL,
	"message" text NOT NULL,
	"status" text DEFAULT 'open' NOT NULL,
	"reply" text,
	"replied_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"attachment_key" text,
	"attachment_file_name" text,
	"attachment_mime_type" text,
	"attachment_size" integer
);
--> statement-breakpoint
CREATE TABLE "merchant_users" (
	"user_id" bigint PRIMARY KEY NOT NULL,
	"merchant_key" uuid NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"scope_type" "merchant_scope_type" DEFAULT 'merchant' NOT NULL,
	CONSTRAINT "merchant_users_user_id_merchant_key_unique" UNIQUE("user_id","merchant_key")
);
--> statement-breakpoint
CREATE TABLE "provider_banners" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "provider_banners_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"image_key" text NOT NULL,
	"title" text NOT NULL,
	"subtitle" text NOT NULL,
	"cta" text NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"starts_at" timestamp with time zone,
	"ends_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stg"."list_kota_clean" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"batch_id" uuid NOT NULL,
	"row_num" integer NOT NULL,
	"region" text NOT NULL,
	"branch" text NOT NULL,
	"cluster" text NOT NULL,
	"cluster_id" bigint NOT NULL,
	"raw_payload" jsonb NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stg"."list_kota_raw" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"batch_id" uuid NOT NULL,
	"row_num" integer NOT NULL,
	"raw_payload" jsonb NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stg"."master_clean" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"batch_id" uuid NOT NULL,
	"row_num" integer NOT NULL,
	"uniq_merchant" text NOT NULL,
	"merchant_name" text NOT NULL,
	"keyword" text NOT NULL,
	"category" text NOT NULL,
	"point_redeem" integer NOT NULL,
	"start_period" date NOT NULL,
	"end_period" date NOT NULL,
	"region" text NOT NULL,
	"branch" text NOT NULL,
	"cluster" text NOT NULL,
	"merchant_key" uuid NOT NULL,
	"category_id" integer NOT NULL,
	"cluster_id" bigint NOT NULL,
	"rule_key" uuid NOT NULL,
	"raw_payload" jsonb NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stg"."master_raw" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"batch_id" uuid NOT NULL,
	"row_num" integer NOT NULL,
	"raw_payload" jsonb NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stg"."total_point_clean" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"batch_id" uuid NOT NULL,
	"row_num" integer NOT NULL,
	"point_key" uuid NOT NULL,
	"cluster" text NOT NULL,
	"cluster_id" bigint NOT NULL,
	"month_year" date NOT NULL,
	"total_point" bigint NOT NULL,
	"point_owner" bigint NOT NULL,
	"raw_payload" jsonb NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stg"."total_point_raw" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"batch_id" uuid NOT NULL,
	"row_num" integer NOT NULL,
	"raw_payload" jsonb NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stg"."transactions_clean" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"batch_id" uuid NOT NULL,
	"row_num" integer NOT NULL,
	"transaction_key" uuid NOT NULL,
	"transaction_at" timestamp NOT NULL,
	"keyword" text NOT NULL,
	"msisdn" text NOT NULL,
	"qty" integer NOT NULL,
	"status" text NOT NULL,
	"raw_payload" jsonb NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stg"."transactions_raw" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"batch_id" uuid NOT NULL,
	"row_num" integer NOT NULL,
	"raw_payload" jsonb NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"email" text NOT NULL,
	"username" text,
	"password_hash" text NOT NULL,
	"role" text DEFAULT 'merchant' NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_email_unique" UNIQUE("email"),
	CONSTRAINT "users_username_unique" UNIQUE("username")
);
--> statement-breakpoint
ALTER TABLE "admin_sessions" ADD CONSTRAINT "admin_sessions_user_id_admin_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."admin_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit"."batch_issue_links" ADD CONSTRAINT "batch_issue_links_batch_id_batches_batch_id_fk" FOREIGN KEY ("batch_id") REFERENCES "audit"."batches"("batch_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit"."batch_issue_links" ADD CONSTRAINT "batch_issue_links_issue_id_ingestion_issues_issue_id_fk" FOREIGN KEY ("issue_id") REFERENCES "audit"."ingestion_issues"("issue_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dim_merchant" ADD CONSTRAINT "dim_merchant_cluster_id_dim_cluster_cluster_id_fk" FOREIGN KEY ("cluster_id") REFERENCES "public"."dim_cluster"("cluster_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dim_merchant" ADD CONSTRAINT "dim_merchant_category_id_dim_category_category_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."dim_category"("category_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dim_rule" ADD CONSTRAINT "dim_rule_rule_merchant_dim_merchant_merchant_key_fk" FOREIGN KEY ("rule_merchant") REFERENCES "public"."dim_merchant"("merchant_key") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fact_cluster_point" ADD CONSTRAINT "fact_cluster_point_cluster_id_dim_cluster_cluster_id_fk" FOREIGN KEY ("cluster_id") REFERENCES "public"."dim_cluster"("cluster_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fact_transaction" ADD CONSTRAINT "fact_transaction_rule_key_dim_rule_rule_key_fk" FOREIGN KEY ("rule_key") REFERENCES "public"."dim_rule"("rule_key") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fact_transaction" ADD CONSTRAINT "fact_transaction_merchant_key_dim_merchant_merchant_key_fk" FOREIGN KEY ("merchant_key") REFERENCES "public"."dim_merchant"("merchant_key") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "merchant_feedback" ADD CONSTRAINT "merchant_feedback_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "merchant_users" ADD CONSTRAINT "merchant_users_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "admin_sessions_expires_at_idx" ON "admin_sessions" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "admin_sessions_user_id_idx" ON "admin_sessions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "admin_users_active_idx" ON "admin_users" USING btree ("is_active");--> statement-breakpoint
CREATE UNIQUE INDEX "ux_batch_issue_links_batch_row_issue" ON "audit"."batch_issue_links" USING btree ("batch_id","row_num","issue_id");--> statement-breakpoint
CREATE INDEX "idx_batch_issue_links_batch_state" ON "audit"."batch_issue_links" USING btree ("batch_id","state");--> statement-breakpoint
CREATE INDEX "idx_batch_issue_links_issue_state" ON "audit"."batch_issue_links" USING btree ("issue_id","state");--> statement-breakpoint
CREATE UNIQUE INDEX "ux_batches_public_id" ON "audit"."batches" USING btree ("batch_public_id");--> statement-breakpoint
CREATE INDEX "idx_batches_created_at" ON "audit"."batches" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_batches_dataset_status" ON "audit"."batches" USING btree ("dataset","status");--> statement-breakpoint
CREATE UNIQUE INDEX "ux_ingestion_issues_fingerprint" ON "audit"."ingestion_issues" USING btree ("issue_fingerprint");--> statement-breakpoint
CREATE INDEX "idx_ingestion_issues_status" ON "audit"."ingestion_issues" USING btree ("status","dataset");--> statement-breakpoint
CREATE INDEX "idx_ingestion_issues_conflict_scope" ON "audit"."ingestion_issues" USING btree ("issue_kind","conflict_merchant_key","conflict_start_period","conflict_end_period");--> statement-breakpoint
CREATE INDEX "dim_merchant_idx_dim_merchant_category_id" ON "dim_merchant" USING btree ("category_id");--> statement-breakpoint
CREATE INDEX "dim_merchant_idx_dim_merchant_cluster_id" ON "dim_merchant" USING btree ("cluster_id");--> statement-breakpoint
CREATE INDEX "dim_rule_idx_dim_rule_merchant" ON "dim_rule" USING btree ("rule_merchant");--> statement-breakpoint
CREATE INDEX "fact_cluster_point_idx_fcp_month_cluster" ON "fact_cluster_point" USING btree ("month_year","cluster_id");--> statement-breakpoint
CREATE INDEX "fact_transaction_idx_ft_merchant_status_time" ON "fact_transaction" USING btree ("merchant_key","status","transaction_at");--> statement-breakpoint
CREATE INDEX "fact_transaction_index_6" ON "fact_transaction" USING btree ("msisdn");--> statement-breakpoint
CREATE INDEX "fact_transaction_rule" ON "fact_transaction" USING btree ("rule_key");--> statement-breakpoint
CREATE INDEX "idx_merchant_feedback_merchant" ON "merchant_feedback" USING btree ("merchant_key");--> statement-breakpoint
CREATE INDEX "idx_merchant_feedback_status" ON "merchant_feedback" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_merchant_feedback_user" ON "merchant_feedback" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_merchant_users_merchant_key" ON "merchant_users" USING btree ("merchant_key");--> statement-breakpoint
CREATE INDEX "idx_provider_banners_active" ON "provider_banners" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_provider_banners_sort" ON "provider_banners" USING btree ("sort_order");--> statement-breakpoint
CREATE INDEX "idx_list_kota_clean_batch" ON "stg"."list_kota_clean" USING btree ("batch_id","row_num");--> statement-breakpoint
CREATE INDEX "idx_list_kota_raw_batch" ON "stg"."list_kota_raw" USING btree ("batch_id","row_num");--> statement-breakpoint
CREATE INDEX "idx_master_clean_batch" ON "stg"."master_clean" USING btree ("batch_id","row_num");--> statement-breakpoint
CREATE INDEX "idx_master_raw_batch" ON "stg"."master_raw" USING btree ("batch_id","row_num");--> statement-breakpoint
CREATE INDEX "idx_total_point_clean_batch" ON "stg"."total_point_clean" USING btree ("batch_id","row_num");--> statement-breakpoint
CREATE UNIQUE INDEX "total_point_clean_batch_row_month_unique" ON "stg"."total_point_clean" USING btree ("batch_id","row_num","month_year");--> statement-breakpoint
CREATE INDEX "idx_total_point_raw_batch" ON "stg"."total_point_raw" USING btree ("batch_id","row_num");--> statement-breakpoint
CREATE INDEX "idx_transactions_clean_batch" ON "stg"."transactions_clean" USING btree ("batch_id","row_num");--> statement-breakpoint
CREATE INDEX "idx_transactions_raw_batch" ON "stg"."transactions_raw" USING btree ("batch_id","row_num");