CREATE TABLE "program_banner_assets" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "program_banner_assets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"rule_key" uuid,
	"keyword_code" text,
	"image_url" text NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "program_banner_assets_target_check" CHECK (num_nonnulls(rule_key, keyword_code) = 1)
);
--> statement-breakpoint
ALTER TABLE "provider_banners" RENAME COLUMN "image_key" TO "image_url";--> statement-breakpoint
ALTER TABLE "program_banner_assets" ADD CONSTRAINT "program_banner_assets_rule_key_dim_rule_rule_key_fk" FOREIGN KEY ("rule_key") REFERENCES "public"."dim_rule"("rule_key") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "program_banner_assets" ADD CONSTRAINT "program_banner_assets_keyword_code_dim_merchant_keyword_code_fk" FOREIGN KEY ("keyword_code") REFERENCES "public"."dim_merchant"("keyword_code") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_program_banner_assets_active" ON "program_banner_assets" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_program_banner_assets_keyword_code" ON "program_banner_assets" USING btree ("keyword_code");--> statement-breakpoint
CREATE INDEX "idx_program_banner_assets_rule_key" ON "program_banner_assets" USING btree ("rule_key");--> statement-breakpoint
CREATE UNIQUE INDEX "program_banner_assets_rule_key_unique" ON "program_banner_assets" USING btree ("rule_key");--> statement-breakpoint
CREATE UNIQUE INDEX "program_banner_assets_keyword_code_unique" ON "program_banner_assets" USING btree ("keyword_code");